<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Title>BetSniffer</Title>
    <Version>25.03.27.1</Version>
    <ApplicationIcon>Utils\XeiraBet.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Utils\XeiraBet.ico" />
	<Content Include="Frontend\**\*">
	 <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	</Content>
  </ItemGroup>

  <ItemGroup>
    <None Remove="Frontend\Components\Monitor.html" />
    <None Remove="Frontend\Components\Scraping.html" />
    <None Remove="Frontend\Scripts\arbitrage.js" />
    <None Remove="Frontend\Scripts\main.js" />
    <None Remove="Frontend\Scripts\monitor.js" />
    <None Remove="Frontend\Scripts\scraper.js" />
    <None Remove="Frontend\Scripts\TabControl.js" />
    <None Remove="Frontend\Scripts\updateGames.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="PuppeteerSharp" Version="20.0.5" />
    <PackageReference Include="Selenium.WebDriver" Version="4.27.0" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="131.0.6778.10800" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Frontend\Assets\images\" />
    <Folder Include="Frontend\Assets\fonts\" />
  </ItemGroup>

</Project>
